language: python

python:
  - 2.7

sudo: required

services:
  - docker

env:
  global:
  - REPO=driesschulten/pandas
  - secure: NDb/NsnyWcWJANMWq6Za70ZBQI4p9tBjB4P+hWzEQhX/tkzhpjEq5YFF3qxgPS0tUX40o1YJ0QKH5qunWxl+I9Z4UKAc4N/DrPsvbRqM4mPTHtJT+/Ptmo6RT8MPYuOogFTZhMMUqknLnUmM9EF1ypYC3/7K1N1naPX/KkwhuQJIFCW0Nms7X1waSSazvFCe/31hV46VJ+hihFW0RUZRmyaru6HMaiM2HJiSQ00xJWWj788d7Qbt9XRqqvqyILcUzu797j4SyNwDyyjyl20wZ3cRGXyd0bK4rz6fZmLfAclFKyfbV6Mc9UTH1alKAMCSHW4AJziZZdZ0EMcdpQ+3vmZ215xBUEiEjFgkodyrJ9bVRC3kUIzxtoiZ+3yPK5d5bmBpVSABTXgSJFz1aSBb68sLpnldCpzxzQAnr9Sluj2p4+j8lEJrUcclvy4HeQqNR/NxYjCgdOd/xs46VvtOaH76hvQRk9tcfTPVfCUu+YDG5qI9ahP+7l+D3n3KwC4QLCMfZYACmsB0jeejISZlNUQYvoiILGhHOSq2CA70BknH6DWwb1eWOTG7KVyRL6wdPM7Zdu8R0gw7i+euTAuJHx9if0vmrvOviLQ0j+Vq/2c1leqsAbxAns/xRKdM+A6k10t513AuMIMDU5yxzZd2DJKqG641IZacF33mBBqp6bo=
  - secure: KlhjzGf95G/HJJQ1hIgxUsdOhbLm38DE6PGGQfnjfA3k5nTGIVC3CpeCNfhVOfB5kCxvNDctLwDuZHX38X3YBMmT04mLto5eOdLDxGzAYUjeuhbLpX0qQtP7RE4VLrVXj3A4GgqL6DWg7yreahnTuEC+svRj6QggK3YURm6kUfstod1VpCHJ0yYUJvUtijZZPT79QyATAjbC+trer2fRHEE82pe6V86KsOn8taw0OvG4z9O6FHq0dRHQsf9KJvIQtgqdhWcEXcnZGxyrHgIIbQWZvOwuhiuhKGq52GSdBU2qhQ/Dn6Q+v9pS0kds/+lSiaA/VbVeyREnujmGX2ZyECP82oNKQSLMf2+kSpSfY4hnOZpKZaxvulfHiOCgbNek14z/ARkAAwsEp8doRlLVUs2bNqHMOyj+mtGfjZAaE1yAtEhInXp4CrIR/WwYAv8U+sejc618GRvjuEORRFuIdKugkJE8n4xsUdoV9v9yQalyMEiAJ8AdnQbOiSm8CYdBElwnxdvtgrw8dQsQvlDrZLiJ7tWMIHFWeRckAe1NUhLWuiur0Uai1S6jbH1oOUpWKCjGPz0BlT/ni4ElBlktAzSpvE0PUOsWZIq/UA9lsa02Qv+ZFA4YVg8LEEdU/4Wa+OXaLD0b10e6FXDIGC1aszzmqlcSe7Z6xrIDxCHOOjA=

install:
  - docker build -t $REPO .

script: echo 'no tests!'

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker tag $REPO $REPO:latest
  - if [[ $TRAVIS_TAG ]]; then docker tag $REPO $REPO:$TRAVIS_TAG; fi
  - docker push $REPO
